<?php

class MWB_M4WP_Mautic_Api{
    
    //mautic base url
    private $base_url ;
    
    //mautic user_name
    private $user_name;
    
    //mautic password
    private $password;

    //last request
    private $last_request ; 

    //last response
    private $last_response ; 
    
    /**
    * Constructor.
    * @param string $base_url Base url of your mautic instance.
    * @param string $user_name Mautic user name.
    * @param string $password Mautic password.
    */
    public function __construct ( $base_url, $user_name, $password ){
        
        $this->base_url = $base_url. 'api/' ; 
        $this->user_name = $user_name ; 
        $this->password = $password ; 
        
    }
    
    /**
    * Get Request.
    * @param string $endpoint Api endpoint of mautic.
    * @param array  $data Data to be used in request.
    */
    public function get( $endpoint, $data = array() ){
        return $this->request( 'GET', $endpoint, $data ) ; 
    }

    /**
    * Post Request.
    * @param string $endpoint Api endpoint of mautic.
    * @param array  $data Data to be used in request.
    */
    public function post( $endpoint, $data = array() ){
        return $this->request( 'POST', $endpoint, $data ) ; 
    }
    
    /**
    * Send mautic api request
    * @param string $method   HTTP method.
    * @param string $endpoint Api endpoint.
    * @param array  $data     Request data.
    * 
    */
    private function request( $method, $endpoint, $data = array() ){
        
        $this->reset_request_data();
        
        if ( empty( $this->base_url ) ) {
            //throw exception
        }
        if ( empty( $this->user_name ) ) {
            //throw exception
        }
        if ( empty( $this->password ) ) {
            //throw exception
        }
        
        $method = strtoupper( trim( $method ) );
        $url    = $this->base_url . ltrim( $endpoint, '/' );
        $args   = array(
            'method'    => $method,
            'headers'   => $this->get_headers(),
            'timeout'   => 20,
            'sslverify' => apply_filters( 'mwb_m4wp_use_sslverify', true ),
        );

        if ( ! empty( $data ) ) {
            if ( in_array( $method, array( 'GET', 'DELETE' ), true ) ) {
                $url = add_query_arg( $data, $url );
            } else {
                $args['headers']['Content-Type'] = 'application/json';
                $args['body']                    = json_encode( $data );
            }
        }
        
        /**
        * Filter the request arguments for all requests generated by this class
        *
        * @param array $args
        */
        $args = apply_filters( 'mwb_m4wp_http_request_args', $args, $url );
        
        // perform request
        $response = wp_remote_request( $url, $args );

        $args[ 'url' ]         = $url ;
        $args[ 'method' ]      = $method ; 
		$this->last_request    = $args ;
        $this->last_response   = $response ;
        
        // parse response
		$data = $this->parse_response( $response );

		return $data;
    }
    
    /**
    * Get headers. 
    * @return array
    */
    private function get_headers(){
        global $wp_version;
        $headers = array(
            'Authorization' => sprintf( 'Basic %s', base64_encode( $this->user_name . ':' . $this->password ) ),
            'User-Agent'    => sprintf( 'MWB_M4WP/%s; WordPress/%s; %s', MWB_M4WP_VERSION, $wp_version, home_url() ),
        );
        // Copy Accept-Language from browser headers
        if ( ! empty( $_SERVER['HTTP_ACCEPT_LANGUAGE'] ) ) {
            $headers['Accept-Language'] = $_SERVER['HTTP_ACCEPT_LANGUAGE'];
        }        
        return $headers;
    }

    /**
     * Parse response and get back the data
     * @param array $response HTTP response 
    */
    private function parse_response( $response ){
        if ( $response instanceof WP_Error ) {
			//throw expection
        }
        // decode response body
		$code    = (int) wp_remote_retrieve_response_code( $response );
		$message = wp_remote_retrieve_response_message( $response );
        $body    = wp_remote_retrieve_body( $response );
        $data    = json_decode( $body , ARRAY_A ); 
        $this->create_error_log( $code , $message , $data ) ;
        return $data ; 
    }

    /**
     * Log error 
     * @param string $code Http response code.
     * @param string $message Response message.
     * @param array  $data Reponse data.
    */
    public function create_error_log( $code , $message , $data ){
        $file = MWB_M4WP_PLUGIN_PATH.'/error.log' ; 
        $log =  "Url : ". $this->last_request[ 'url' ] . PHP_EOL ;
        $log .= "Method : ". $this->last_request[ 'method' ] . PHP_EOL ; 
        $log .= "Code : $code".PHP_EOL ; 
        $log .= "Message : $message".PHP_EOL ; 
        if( isset( $data[ 'errors' ] ) && is_array( $data[ 'errors' ] ) ){
            foreach( $data[ 'errors' ] as $key => $value ){
                $log .= "Error : " . $value['message'] . PHP_EOL ; 
            }
        } 
        $log .= "Time: ".current_time("F j, Y  g:i a").PHP_EOL ; 
        $log .= "------------------------------------".PHP_EOL ;  
        file_put_contents( $file , $log, FILE_APPEND ) ;
    }

    /**
     * Reset last request data
    */
    private function reset_request_data(){
        $this->last_request = '' ; 
        $this->last_response = '' ; 
    }
}